/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DllBridge */

#ifndef _Included_DllBridge
#define _Included_DllBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DllBridge
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_DllBridge_init
  (JNIEnv *, jobject);

/*
 * Class:     DllBridge
 * Method:    Update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DllBridge_Update
  (JNIEnv *, jobject);

/*
 * Class:     DllBridge
 * Method:    getY
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DllBridge_getY
  (JNIEnv *, jobject, jint);

/*
 * Class:     DllBridge
 * Method:    getX
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DllBridge_getX
  (JNIEnv *, jobject, jint);

/*
 * Class:     DllBridge
 * Method:    getTaste
 * Signature: (IC)Z
 */
JNIEXPORT jboolean JNICALL Java_DllBridge_getTaste
  (JNIEnv *, jobject, jint, jchar);

#ifdef __cplusplus
}
#endif
#endif
